services:
  test-cakephp-app-php7.4-cli:
      build: images/tests/app/php7.4-cli/.
      container_name: test-cakephp-app-php7.4-cli
      ports:
        - "9074:8765"

  test-cakephp-app-php8.0-cli:
      build: images/tests/app/php8.0-cli/.
      container_name: test-cakephp-app-php8.0-cli
      ports:
        - "9080:8765"

  test-cakephp-app-php8.1-cli:
      build: images/tests/app/php8.1-cli/.
      container_name: test-cakephp-app-php8.1-cli
      ports:
        - "9081:8765"

  test-cakephp-app-php8.2-cli:
      build: images/tests/app/php8.2-cli/.
      container_name: test-cakephp-app-php8.2-cli
      ports:
        - "9082:8765"

  test-cakephp-app-php8.3-cli:
      build: images/tests/app/php8.3-cli/.
      container_name: test-cakephp-app-php8.3-cli
      ports:
        - "9083:8765"

  test-cakephp-app-php7.4-apache:
      build: images/tests/app/php7.4-apache/.
      container_name: test-cakephp-app-php7.4-apache
      ports:
        - "8074:80"

  test-cakephp-app-php8.0-apache:
      build: images/tests/app/php8.0-apache/.
      container_name: test-cakephp-app-php8.0-apache
      ports:
        - "8080:80"

  test-cakephp-app-php8.1-apache:
      build: images/tests/app/php8.1-apache/.
      container_name: test-cakephp-app-php8.1-apache
      ports:
        - "8081:80"

  test-cakephp-app-php8.2-apache:
      build: images/tests/app/php8.2-apache/.
      container_name: test-cakephp-app-php8.2-apache
      ports:
        - "8082:80"

  test-cakephp-app-php8.3-apache:
      build: images/tests/app/php8.3-apache/.
      container_name: test-cakephp-app-php8.3-apache
      ports:
        - "8083:80"

  test-apache:
    build: tests/.
    container_name: test-apache
    links:
      - test-cakephp-app-php7.4-apache
      - test-cakephp-app-php8.0-apache
      - test-cakephp-app-php8.1-apache
      - test-cakephp-app-php8.2-apache
      - test-cakephp-app-php8.3-apache
