
test-cakephp-app-php7.2-cli:
    build: images/tests/app/php7.2/.
    container_name: test-cakephp-app-php7.2-cli
    ports:
      - "8765:8765"

test-cakephp-app-php7.3-cli:
    build: images/tests/app/php7.3/.
    container_name: test-cakephp-app-php7.3-cli
    ports:
      - "8766:8765"

test-cakephp-app-php7.4-cli:
    build: images/tests/app/php7.4/.
    container_name: test-cakephp-app-php7.4-cli
    ports:
      - "8767:8765"

test-cakephp-app-php8.0-cli:
    build: images/tests/app/php8.0/.
    container_name: test-cakephp-app-php8.0-cli
    ports:
      - "8768:8765"
