version: 2
jobs:
    test:
        machine: true
        steps:
          - checkout
          - run: |
            docker-compose -f build/docker-compose.test.yml -p ci build
            docker-compose -f build/docker-compose.test.yml -p ci up -d
            cd tests && ./test.sh && cd ../

    deploy:
        machine: true
        steps:
          - checkout
          - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f build/docker-compose.yml -p ci build
            docker tag ci_bionic-lamp:latest 302dev/bionic-lamp:latest
            docker tag ci_bionic-lamp-php73:latest 302dev/bionic-lamp:php7.3
            docker tag ci_bionic-lamp-php72:latest 302dev/bionic-lamp:php7.2
            docker tag ci_xenial-lamp:latest 302dev/xenial-lamp:latest
            docker tag ci_xenial-lamp-php73:latest 302dev/xenial-lamp:php7.3
            docker tag ci_xenial-lamp-php72:latest 302dev/xenial-lamp:php7.2
            docker tag ci_xenial-lamp-php56:latest 302dev/xenial-lamp:php5.6
            docker tag ci_centos7-lamp:latest 302dev/centos7-lamp:latest
            docker tag ci_centos7-lamp-php73:latest 302dev/centos7-lamp:php7.3
            docker tag ci_centos7-lamp-php72:latest 302dev/centos7-lamp:php7.2
            docker tag ci_centos7-lamp-php56:latest 302dev/centos7-lamp:php5.6
            docker push 302dev/bionic-lamp:latest
            docker push 302dev/bionic-lamp:php7.3
            docker push 302dev/bionic-lamp:php7.2
            docker push 302dev/xenial-lamp:latest
            docker push 302dev/xenial-lamp:php7.3
            docker push 302dev/xenial-lamp:php7.2
            docker push 302dev/xenial-lamp:php5.6
            docker push 302dev/centos7-lamp:latest
            docker push 302dev/centos7-lamp:php7.3
            docker push 302dev/centos7-lamp:php7.2
            docker push 302dev/centos7-lamp:php5.6

workflows:
    version: 2
    test-and-deploy:
        jobs:
            - test
            - deploy:
                requires:
                    - test
            filters:
                branches:
                    only: master
