version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: |
          docker-compose -p ci build
          docker-compose -p ci up -d
          docker images

  deploy:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker-compose -p ci build
          docker tag ci_bionic-php7.3-cli:latest 302dev/cakephp:latest
          docker tag ci_bionic-php7.3-cli:latest 302dev/cakephp:bionic-7.3-cli
          docker tag ci_bionic-php7.2-cli:latest 302dev/cakephp:bionic-7.2-cli
          docker tag ci_xenial-php7.3-cli:latest 302dev/cakephp:xenial-7.3-cli
          docker tag ci_xenial-php7.2-cli:latest 302dev/cakephp:xenial-7.2-cli
          docker push 302dev/cakephp:latest
          docker push 302dev/cakephp:bionic-7.3-cli
          docker push 302dev/cakephp:bionic-7.2-cli
          docker push 302dev/cakephp:xenial-7.3-cli
          docker push 302dev/cakephp:xenial-7.2-cli

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
