######################
# 302dev/test:latest #
######################

FROM ubuntu:bionic

# Use cakephp/app as the test for the images.

# Tests for bionic php 7.2

# Tests for bionic php 7.3

# Tests for centos7 php 7.2

# Tests for centos7 php 7.3
