name: Build and Publish 8.0 Apache

on:
    # should build on pull requests
    pull_request:
        branches:
        - '*'
    #should build and push on commit to master
    push:
        branches:
        - master

jobs:
    # define job to build and publish docker image
    build-and-push-docker-image:
        name: Build Docker image and push to repositories
        # run only when code is compiling and tests are passing
        runs-on: ubuntu-latest

        # steps to perform in job
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # setup Docker buld action
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to Github Packages
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GHCR_PAT }}

            - name: Build fr3nch13702/cakephp:php8.0-apache
              id: docker_build
              uses: docker/build-push-action@v4
              with:
                # relative path to the place where source code with Dockerfile is located
                context: ./images/php-8.0-apache
                # Note: tags has to be all lower-case
                tags: |
                    fr3nch13702/cakephp:php8.0-apache
                    ghcr.io/302dev/docker/cakephp:php8.0-apache
                # build on feature branches, push only on main branch
                push: ${{ github.ref == 'refs/heads/master' }}

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
